baseurl: "http://andygrunwald.com/"
languageCode: "en-us"
title: "Andy Grunwald"
theme: "hugo-type-theme"
# TODO: Fix it
# disqusShortname: "andygrunwald"
googleAnalytics: "UA-64342623-1"
# Posts per page
paginate: 10
permalinks:
  post: /blog/:title/

SectionPagesMenu: "nav"

params:
  author: "Andy Grunwald"
  description: "Andy Grunwald - Software Engineer from Germany"
  keywords: "backend,infrastructure,operations,devops,web development,web engineering"
  copyright: "Andy Grunwald"
  headerText: "Hi, my name is **Andy Grunwald**, a Software Engineer from Germany with a focus on **Backend and Infrastructure**. I am leading the Software Operations Team at [trivago](http://www.trivago.com/)."
  gravatar: "andygrunwald@gmail.com"
  social:
    rss: true
    email: "andygrunwald@gmail.com"
    github: "andygrunwald"
    linkedin: "https://www.linkedin.com/in/andy-grunwald-09aa265a"
    twitter: "andygrunwald"

menu:
  nav:
    - Name: "Public speaking"
      Weight: -90
      Identifier: "public-speaking"
      URL: "/public-speaking/"
    - Name: "Blog"
      Weight: -100
      Identifier: "post"
      URL: "/"